# Site
name: 'HotHotChoco'
description: '노드.js Express 백엔드 개발자를 꿈꿉니다.'
meta_description: 'node.js express back-end'
logo: '/images/logo.png'
favicon: '/images/logo.png'
#baseurl: '/저장소이름/'
google_analytics: ''
disqus: '' #댓글 api 이용시 disqus-id 입력
mailchimp-list: ''

# Authors
authors:
  sal:
    name: 길세현
    display_name: SehyeonGil
    gravatar: 
    email: gil9084@gmail.com
    web: https://sehyeongil.github.io