# Site
name: '세현 일지'
description: '개발이 하고싶어요.'
meta_description: 'node.js express back-end'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: '/저장소이름/'
google_analytics: ''
disqus: '' #댓글 api 이용시 disqus-id 입력
mailchimp-list: ''

# Authors
authors:
  sal:
    name: 길세현
    display_name: SehyeonGil
    gravatar: 
    email: gil9084@gmail.com
    web: https://sehyeongil.github.io